name: Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - saga
#  schedule:
#    - cron: "0 0 * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  VERSION: "v2.6.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: |
          git clone https://github.com/nrfconnect/sdk-nrf nrf
          cd nrf
          git checkout tags/$VERSION
          docker build -t sturnusdesign/fw-nrfconnect-nrf-docker -f ../Dockerfile .

      - name: Build asset_tracker application
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            sturnusdesign/fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker_v2 && west build -p always -b nrf9160dk_nrf9160_ns'

      - uses: actions/upload-artifact@v4
        with:
          name: asset_tracker_v2
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Publish image
        run: |
          cd nrf
          echo $DOCKER_PASSWORD | docker login -u sturnusdesign --password-stdin
          docker images
          docker tag sturnusdesign/fw-nrfconnect-nrf-docker sturnusdesign/fw-nrfconnect-nrf-docker:$VERSION
          docker push -a sturnusdesign/fw-nrfconnect-nrf-docker
